# Generated by Django 3.1.3 on 2021-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicalmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('syndrome', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('combination', models.CharField(max_length=80)),
            ],
            options={
                'unique_together': {('name', 'sex')},
            },
        ),
    ]
