# Generated by Django 3.1.3 on 2021-04-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicalmanagementapp', '0002_medicalrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together={('name',)},
        ),
    ]
