# Generated by Django 3.1.3 on 2021-04-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicalmanagementapp', '0003_auto_20210416_2030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together={('name', 'sex', 'combination', 'syndrome')},
        ),
    ]
